### ISSUE TITLE
GraphQL doesn't compile on Linux Swift 5.4

### ISSUE THREAD

**Issue by adam-fowler** [GraphQLSwift/GraphQL#79]
Using Dockerfile
```
FROM swift:5.4 as build

WORKDIR /build
COPY ./Package.* ./
RUN swift package resolve

# Copy entire repo into container
COPY . .

RUN swift test --enable-test-discovery
```
I get these errors
```
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
#8 8.305         guard number._cfTypeID == CFBooleanGetTypeID() else {
#8 8.305                      ^~~~~~~~~
#8 8.305 Foundation.NSNumber (internal):45:27: note: '_cfTypeID' declared here
#8 8.305     override internal var _cfTypeID: CFTypeID { get }
#8 8.305                           ^
#8 8.305 [148/184] Compiling GraphQL Parser.swift
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
#8 8.305         guard number._cfTypeID == CFBooleanGetTypeID() else {
#8 8.305                      ^~~~~~~~~
#8 8.305 Foundation.NSNumber (internal):45:27: note: '_cfTypeID' declared here
#8 8.305     override internal var _cfTypeID: CFTypeID { get }
#8 8.305                           ^
#8 8.305 [149/184] Compiling GraphQL Source.swift
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
#8 8.305         guard number._cfTypeID == CFBooleanGetTypeID() else {
#8 8.305                      ^~~~~~~~~
#8 8.305 Foundation.NSNumber (internal):45:27: note: '_cfTypeID' declared here
#8 8.305     override internal var _cfTypeID: CFTypeID { get }
#8 8.305                           ^
#8 8.305 [150/184] Compiling GraphQL Visitor.swift
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
...
```

**Comment by alexsteinerde** [comment]
I created a PR that fixes the build issue for me (I used the Dockerfile provided by you).
Please correct me if my solution is wrong.

If a re-write is possible I don't know. I'm not very familiar with the low level code to answer this question.

**Comment by adam-fowler** [comment]
Yeah looks to fix it. I hadn't thought of using `CFGetTypeID`.
Removing `NSNumber` will improve performance of the Coders. But I guess that can be done another time.
