### PR TITLE
Replace `_cfTypeID` with `CFGetTypeID`

### LINKED ISSUE #79: GraphQL doesn't compile on Linux Swift 5.4
Using Dockerfile
```
FROM swift:5.4 as build

WORKDIR /build
COPY ./Package.* ./
RUN swift package resolve

# Copy entire repo into container
COPY . .

RUN swift test --enable-test-discovery
```
I get these errors
```
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
#8 8.305         guard number._cfTypeID == CFBooleanGetTypeID() else {
#8 8.305                      ^~~~~~~~~
#8 8.305 Foundation.NSNumber (internal):45:27: note: '_cfTypeID' declared here
#8 8.305     override internal var _cfTypeID: CFTypeID { get }
#8 8.305                           ^
#8 8.305 [148/184] Compiling GraphQL Parser.swift
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
#8 8.305         guard number._cfTypeID == CFBooleanGetTypeID() else {
#8 8.305                      ^~~~~~~~~
#8 8.305 Foundation.NSNumber (internal):45:27: note: '_cfTypeID' declared here
#8 8.305     override internal var _cfTypeID: CFTypeID { get }
#8 8.305                           ^
#8 8.305 [149/184] Compiling GraphQL Source.swift
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
#8 8.305         guard number._cfTypeID == CFBooleanGetTypeID() else {
#8 8.305                      ^~~~~~~~~
#8 8.305 Foundation.NSNumber (internal):45:27: note: '_cfTypeID' declared here
#8 8.305     override internal var _cfTypeID: CFTypeID { get }
#8 8.305                           ^
#8 8.305 [150/184] Compiling GraphQL Visitor.swift
#8 8.305 /build/Sources/GraphQL/Map/AnyCoder.swift:2058:22: error: '_cfTypeID' is inaccessible due to 'internal' protection level
...
```

### PR DESCRIPTION
**Pull request by alexsteinerde**
because of accessibility change in Swift Foundation

Fixes #79

### CODE REVIEW

**Comment by alexsteinerde** [comment]
Thanks for approving. No, I don't have write access to this repository.

**Comment by paulofaria** [comment]
Yeah, that's weird because when I go to the "checks" tab, all tests have passed and are "green".
